-- CreateTable
CREATE TABLE "amostra_leads" (
    "id"                    TEXT NOT NULL,
    "email"                 TEXT,
    "nome"                  TEXT,
    "telefone"              TEXT,
    "celular"               TEXT,
    "cargo"                 TEXT,
    "empresa"               TEXT NOT NULL,
    "site"                  TEXT,
    "plataforma_do_site"    TEXT,
    "status_serpapi"        TEXT NOT NULL DEFAULT 'pending',
    "status_apollo"         TEXT NOT NULL DEFAULT 'pending',
    "status_apify"          TEXT NOT NULL DEFAULT 'pending',
    "status_hunter"         TEXT NOT NULL DEFAULT 'pending',
    "site_encontrado"       TEXT,
    "email_decisor"         TEXT,
    "cargo_decisor"         TEXT,
    "linkedin_decisor"      TEXT,
    "telefone_decisor"      TEXT,
    "tamanho_empresa"       TEXT,
    "tecnologias"           TEXT,
    "whatsapp_apify"        TEXT,
    "instagram_apify"       TEXT,
    "facebook_apify"        TEXT,
    "email_empresa_apify"   TEXT,
    "email_hunter"          TEXT,
    "email_hunter_score"    INTEGER,
    "erro_serpapi"          TEXT,
    "erro_apollo"           TEXT,
    "erro_apify"            TEXT,
    "erro_hunter"           TEXT,
    "score_enriquecimento"  INTEGER NOT NULL DEFAULT 0,
    "created_at"            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"            TIMESTAMP(3) NOT NULL,

    CONSTRAINT "amostra_leads_pkey" PRIMARY KEY ("id")
);
